name: demo github actions
on:
  push:
    branches: [develop]
  pull_request:
    types: [opened, closed, synchronize]
jobs:
  jobs_1: 
    runs-on: ubuntu-latest
    steps:
      # - name: in ra cau lenh helo
      # - run: echo bao c.an ba tien ca do 
      - name: Checkout 
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
         node-version: 14
      - name: install node_module
        run: npm i
      # - run: npm run lint
      - name: Using action reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'src/'
      
  