name: demo github actions
on:
  push:
    # paths:
    #   - "!README.md"
    #   - "feature/**"
    #   - "!docs/**"
    branches: [develop]
  pull_request:
    types: [opened, closed, synchronize]
env:
  SURGE_DOMAIN: demo-fe-github-action.surge.sh
jobs:
  jobs_1: 
    runs-on: ubuntu-latest
    steps:
      # - name: in ra cau lenh helo
      # - run: echo bao c.an ba tien ca do 
      - name: Checkout 
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
         node-version: 14
      - name: install node_module
        run: npm i
      # - run: npm run lint
      - name: Using action reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'src/'
      - name: deploy surge
        run: npm install -g surge
      - run: surge ./ $SURGE_DOMAIN --token ${{ secrets.SURGE_TOKEN }}
  # demo-fe-github-action.surge.sh
